pipeline:
  clone:
    image: plugins/git
    depth: 1

  analysis:
    image: rips/rips-cli
    secrets:  [rips_username, rips_password, test]
    commands:
      - export RIPS_BASE_URI='https://api-2.ripstech.com'
      - export RIPS_USERNAME=$RIPS_USERNAME
      - export RIPS_PASSWORD=$RIPS_PASSWORD
      - rips-cli rips:scan:start -a 21004 -Q 520 -p $(pwd) -t 1 -T $DRONE_REPO_OWNER-$DRONE_BRANCH ||  { echo "Please contact the security team at security@joomla.org"; exit 1; }

  phpcs:
    image: joomlaprojects/docker-phpcs
    commands:
      - echo $(date)
      - /root/.composer/vendor/bin/phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla .
      - echo $(date)

  initdb:
    image: joomlaprojects/docker-php70:develop
    commands:
      - composer install
      - /bin/bash ./build/drone/database-setup.sh

  php70:
    group: php
    image: joomlaprojects/docker-php70:develop
    environment:
      - JTEST_DATABASE_MYSQL_DSN="host=mysql;dbname=joomla_70;user=joomla_ut;pass=joomla_ut"
      - JTEST_DATABASE_MYSQLI_DSN="host=mysql;dbname=joomla_70;user=joomla_ut;pass=joomla_ut"
      - JTEST_DATABASE_PDO_MYSQL_DSN="host=mysql;dbname=joomla_70;user=joomla_ut;pass=joomla_ut"
      - JTEST_DATABASE_POSTGRESQL_DSN="host=postgres;port=5432;dbname=joomla_70;user=postgres;pass="
    commands:
      - echo $(date)
      - JTEST_DATABASE_MYSQL_DSN="host=mysql;dbname=joomla_70;user=joomla_ut;pass=joomla_ut"
      - JTEST_DATABASE_MYSQLI_DSN="host=mysql;dbname=joomla_70;user=joomla_ut;pass=joomla_ut"
      - JTEST_DATABASE_PDO_MYSQL_DSN="host=mysql;dbname=joomla_70;user=joomla_ut;pass=joomla_ut"
      - JTEST_DATABASE_POSTGRESQL_DSN="host=postgres;port=5432;dbname=joomla_70;user=postgres;pass="
      - ./libraries/vendor/bin/phpunit --configuration ./libraries/vendor/joomla/test-unit/phpunit.xml.dist
      - echo $(date)


  javascript:
    image: joomlaprojects/docker-systemtests:latest
    commands:
      - echo $(date)
      - apt-get install nodejs npm
      - ln -s /usr/bin/nodejs /usr/bin/node
      - export DISPLAY=:0
      - Xvfb -screen 0 1024x768x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
      - sleep 3
      - fluxbox  > /dev/null 2>&1 &
      - cd tests/javascript
      - npm install
      - cd ../..
      - tests/javascript/node_modules/karma/bin/karma start karma.conf.js --single-run
      - echo $(date)

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut

  memcached:
    image: memcached:alpine

  redis:
    image: redis:alpine

  postgres:
    image: postgres